baseURL = "https://es.tianheg.org/"
languageCode = "zh-CN"
defaultContentLanguage = "en"

title = "ECMAScript manual"
theme = "learn"

[params]
  editURL = "https://github.com/tianheg/ecmascript/edit/main/content/"
  description = "My ECMAScript manual"
  author = "tianheg"
  showVisitedLinks = false
  disableBreadcrumb = false
  disableNextPrev = false
  disableLandingPageButton = true
  disableMermaid = false
  customMermaidURL = "https://unpkg.com/mermaid@8.8.0/dist/mermaid.min.js"
  disableLanguageSwitchingButton = true

[outputs]
home = [ "HTML", "RSS", "JSON"]
